"""Add is_admin column to User model

Revision ID: 592c3d861729
Revises: f20bd8c4b3fb
Create Date: 2024-04-21 20:13:04.250713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592c3d861729'
down_revision = 'f20bd8c4b3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
